id: d4d80779-e5ac-4e0a-b8fb-4cdfd4474720
title: Time of day (60x Slower - 24 Hours)
subtitle:
description:
version: 1.0.0
category: 5
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.2
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

