id: 0a7d4832-77cf-47a8-9d52-0d33e8e6c730
title: Time of day (4x Faster - 6 Minutes)
subtitle:
description:
version: 1.0.0
category: 5
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.2
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

