id: 676b3a73-c06e-467d-9199-cd49dfc60561
title: Time of day (1.5x Slower - 36 Minutes)
subtitle:
description:
version: 1.0.0
category: 5
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.2
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

