id: 358d9165-35dc-4e2a-824e-c584b1056da6
title: Time of day (30x Slower - 12 Hours)
subtitle:
description:
version: 1.0.0
category: 5
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.2
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

