id: 9ce0b2f4-ae88-43cd-8b7c-abc35bdb5b85
title: Time of day (2.5x Slower - 60 Minutes)
subtitle:
description:
version: 1.0.0
category: 5
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.2
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

